import { Field, FarmerAlert, AdvisoryPlan, Diagnosis } from '../types';

export const initialMockUser = {
  id: 101,
  name: 'Rajesh Patil',
  phone: '9876543210',
  role: 'farmer' as const,
  language: 'mr' as const,
  village: 'Patur',
  taluka: 'Barshitakli',
  district: 'Akola, Vidarbha',
};

export const initialMockFields: Field[] = [
  {
    id: 1,
    name: 'Cotton — Field 1',
    crop: 'Cotton',
    variety: 'Bt Cotton (RCH-659)',
    growth_stage: 'Flowering & Boll formation',
    soil_type: 'Black Cotton Soil (Regur)',
    area_acres: 5,
    location: 'Akola, Vidarbha',
    lat: 20.7002,
    lng: 77.0082,
    created_at: '2026-05-20T00:00:00Z',
    latest_risk: {
      field_id: 1,
      risk_level: 'HIGH',
      risk_score: 0.78,
      irrigation: 'WAIT',
      reason: 'Rain expected tomorrow. Disease risk is elevated.',
      computed_at: '2026-09-02T10:00:00Z',
    },
    latest_diagnosis: {
      diagnosis_id: 45,
      field_id: 1,
      field_name: 'Cotton — Field 1',
      crop: 'Cotton',
      disease: 'Early Blight',
      confidence: 0.91,
      status: 'Disease Detected',
      routed_to: 'farmer',
      created_at: '2026-09-02T10:30:00Z',
      image_url: 'https://images.unsplash.com/photo-1597848212624-a19eb35e2651?w=600&auto=format&fit=crop&q=80',
    },
  },
  {
    id: 2,
    name: 'Soybean — Field 2',
    crop: 'Soybean',
    variety: 'JS-335',
    growth_stage: 'Pod development',
    soil_type: 'Medium Black Soil',
    area_acres: 4,
    location: 'Latur, Marathwada',
    lat: 18.4088,
    lng: 76.5604,
    created_at: '2026-06-10T00:00:00Z',
    latest_risk: {
      field_id: 2,
      risk_level: 'MEDIUM',
      risk_score: 0.42,
      irrigation: 'NORMAL',
      reason: 'Moderate humidity with dry spell forecast.',
      computed_at: '2026-09-02T09:00:00Z',
    },
    latest_diagnosis: {
      diagnosis_id: 46,
      field_id: 2,
      field_name: 'Soybean — Field 2',
      crop: 'Soybean',
      disease: 'Unknown Leaf Spot',
      confidence: 0.62,
      status: 'pending_review',
      routed_to: 'officer',
      created_at: '2026-09-01T15:20:00Z',
      image_url: 'https://images.unsplash.com/photo-1530595467537-0b5996c41f2d?w=600&auto=format&fit=crop&q=80',
      officer_notes: 'Under review by Taluka Agricultural Officer (MPKV Rahuri Extension).',
    },
  },
  {
    id: 3,
    name: 'Pigeonpea (Tur) — Field 3',
    crop: 'Pigeonpea (Tur)',
    variety: 'BDN-711',
    growth_stage: 'Vegetative growth',
    soil_type: 'Loamy Alluvial',
    area_acres: 3,
    location: 'Chandrapur, Vidarbha',
    lat: 19.9615,
    lng: 79.2961,
    created_at: '2026-06-25T00:00:00Z',
    latest_risk: {
      field_id: 3,
      risk_level: 'LOW',
      risk_score: 0.18,
      irrigation: 'IRRIGATE',
      reason: 'Dry clear skies for next 4 days. Soil moisture is dropping.',
      computed_at: '2026-09-02T08:00:00Z',
    },
    created_at_str: '2026-06-25T00:00:00Z',
  } as Field,
];

export const mockAdvisories: Record<string, AdvisoryPlan> = {
  'Early Blight': {
    disease: 'Early Blight',
    crop: 'Cotton',
    steps: [
      'Remove visibly infected leaves with brown circular spots and destroy them away from field.',
      'Apply neem-based spray (NSKE 5% or 10,000 ppm @ 3ml/L) or Copper Oxychloride 50 WP (2.5g/L) during calm morning hours.',
      'Monitor crop daily for 5 days. Ensure adequate spacing and avoid overhead furrow flooding.',
      'Contact Taluka Agriculture Officer if yellow rings continue spreading after 5 days.',
    ],
    escalate_if: 'Symptoms continue spreading after 5 days or lesion covers more than 30% of foliage.',
    organic_treatment: 'Neem Oil 10,000 ppm (30ml per 10L pump) + Dashparni Kadha',
    chemical_treatment: 'Copper Oxychloride 50% WP (25g per 10L water)',
    caution: 'Avoid spraying during strong winds or direct hot midday sun. Wear protective mask.',
  },
  'Cotton Leaf Curl': {
    disease: 'Cotton Leaf Curl',
    crop: 'Cotton',
    steps: [
      'Uproot and bury severely stunted plants showing upward leaf curling.',
      'Control whitefly vectors using yellow sticky traps (10 traps per acre).',
      'Spray neem seed extract (5%) to disrupt nymph multiplication.',
      'Escalate if leaf veins show thick green enation across multiple plant clusters.',
    ],
    escalate_if: 'Whitefly counts exceed 8 per leaf or curling spreads to adjacent rows.',
  },
  'Yellow Mosaic Virus': {
    disease: 'Yellow Mosaic Virus',
    crop: 'Soybean',
    steps: [
      'Rogue out and destroy affected plants showing mottled yellow chlorosis immediately.',
      'Install yellow sticky traps (8-10 per acre) at crop canopy level to check whiteflies.',
      'Monitor for 5 days to confirm whether young uninfected leaves stay green.',
      'Escalate to extension officer if more than 5% of the plot exhibits yellowing.',
    ],
    escalate_if: 'Yellowing spreads rapidly to newer upper foliage within 5 days.',
  },
};

export const initialMockAlerts: FarmerAlert[] = [
  {
    id: 101,
    type: 'HIGH_RISK',
    title: '⚠️ HIGH RISK: Cotton — Field 1',
    message: 'Rain expected tomorrow. Disease risk is elevated.',
    field_id: 1,
    field_name: 'Cotton — Field 1',
    is_read: false,
    created_at: '2026-09-02T10:00:00Z',
    action_url: '/fields/1',
  },
  {
    id: 102,
    type: 'DIAGNOSIS_READY',
    title: '🌱 DIAGNOSIS READY: Cotton Scan',
    message: 'Your crop scan has been analyzed. Early Blight detected (91% AI confidence).',
    field_id: 1,
    field_name: 'Cotton — Field 1',
    diagnosis_id: 45,
    disease: 'Early Blight',
    is_read: false,
    created_at: '2026-09-02T10:32:00Z',
    action_url: '/diagnosis/45',
  },
  {
    id: 103,
    type: 'EXPERT_REVIEW',
    title: '👨‍🌾 EXPERT REVIEW: Soybean Case #46',
    message: 'Your crop case is being reviewed by an agriculture officer.',
    field_id: 2,
    field_name: 'Soybean — Field 2',
    diagnosis_id: 46,
    is_read: true,
    created_at: '2026-09-01T15:25:00Z',
    action_url: '/diagnosis/46',
  },
];
