export const ADVISORY_DB = {
  "Blast": { crop: "Rice", steps: ["Use disease-free seeds Indrayani/Swarna","Avoid excess N - keep N 80-100 kg/ha as per Soil_Nutrient data","Spray Tricyclazole 75% WP @0.6g/l","Drain water periodically","Destroy crop residue"], escalate_if: "lesions increase >10% after 7 days", followup_days: 7, chemical: "Tricyclazole 75% WP @0.6g/l - 15 days waiting", safety: "PPE + spray evening" },
  "Bacterial Blight": { crop: "Rice", steps: ["Avoid clipping leaf tips","Balanced NPK - P 50-60 from SoilHealth portal","Spray Copper Oxychloride + Streptocycline","Early sowing June 15-30"], escalate_if: "yellowing spreads to whole field", followup_days: 5, chemical: "Copper Oxychloride", safety: "Don't enter 24h after spray" },
  "Brown Spot": { crop: "Rice", steps: ["Seed treatment with Mancozeb","Apply FYM 5t/ha - low Organic Carbon","Spray Propiconazole"], escalate_if: "spots cover >25% leaf area", followup_days: 7, chemical: "Propiconazole 25% EC @1ml/l", safety: "Moderate toxicity" },
  "Bollworm": { crop: "Cotton", steps: ["Install pheromone traps @5/acre - from Crop_and_fertilizer_dataset 4513 rows","Release Trichogramma @1.5 lakh/ha","Handpick & destroy larvae","ETL: 5% boll damage","Intercrop with pigeon pea as per Springer division"], escalate_if: "boll damage >10%", followup_days: 5, chemical: "Emamectin Benzoate 5% SG @0.4g/l OR Spinosad 45% SC", safety: "Very toxic - full PPE, 14 days waiting" },
  "Aphid": { crop: "Cotton", steps: ["Spray strong water jet","Use yellow sticky traps","Spray Imidacloprid 17.8% SL @0.3ml/l if >10% infestation"], escalate_if: "curling continues after 4 days", followup_days: 4, chemical: "Imidacloprid 17.8% SL", safety: "Low toxicity" },
  "Leaf Curl Virus": { crop: "Cotton", steps: ["Control whitefly vector","Remove & burn infected plants","Use resistant variety"], escalate_if: "spreads to >20% plants", followup_days: 7, chemical: "No chemical - vector control only", safety: "N/A" },
  "Yellow Mosaic": { crop: "Soybean", steps: ["Control whitefly with yellow sticky traps @8/acre","Spray Imidacloprid 17.8% SL","Remove & bury infected plants immediately","Sow before 15 July - JS-335 resistant","Maintain yield 1.2 t/ha from Area/Production/Yield"], escalate_if: "yellow >15% field area", followup_days: 4, chemical: "Imidacloprid for whitefly vector", safety: "Wear mask" },
  "Rust": { crop: "Soybean", steps: ["Spray Propiconazole 25% EC","Avoid late sowing"], escalate_if: "pustules on >30% leaves", followup_days: 5, chemical: "Propiconazole 25% EC", safety: "Moderate" },
  "Collar Rot": { crop: "Soybean", steps: ["Seed treatment Trichoderma @10g/kg","Avoid waterlogging - check Soil_Moisture_Percent"], escalate_if: "wilting increases", followup_days: 3, chemical: "Trichoderma (bio)", safety: "Safe - bio agent" },
  "Red Rot": { crop: "Sugarcane", steps: ["Rogue out affected clumps + burn","Drench Carbendazim 50% WP @1g/l","Treat setts 0.1% carbendazim before planting","Use disease-free setts Kolhapur method","Do not use ratoon from infected field","pH 6.5-7.5 ideal - add gypsum if alkaline"], escalate_if: "rot spreads to nearby clumps", followup_days: 10, chemical: "Carbendazim 50% WP @1g/l", safety: "Wash hands after handling" },
  "Wilt": { crop: "Sugarcane", steps: ["Select tolerant variety Co 86032","Avoid water stress - Soil_Moisture 28-35% needed","Drench with Carbendazim"], escalate_if: "wilting >5% clumps", followup_days: 7, chemical: "Carbendazim 50% WP", safety: "Moderate" },
  "Pokkah Boeng": { crop: "Sugarcane", steps: ["Spray Copper Oxychloride","Remove infected tops"], escalate_if: "top rot continues", followup_days: 7, chemical: "Copper Oxychloride", safety: "Low toxicity" },
  "Grain Mold": { crop: "Sorghum", steps: ["Use early maturing variety","Harvest at physiological maturity","Spray Propiconazole"], escalate_if: "mold on >20% grains", followup_days: 5, chemical: "Propiconazole", safety: "Moderate" },
  "Anthracnose": { crop: "Sorghum", steps: ["Seed treatment Captan","Rotate with legume crop"], escalate_if: "lesions on stem", followup_days: 7, chemical: "Mancozeb 75% WP", safety: "PPE required" },
  "Rust_Wheat": { crop: "Wheat", steps: ["Spray Propiconazole 25% EC @1ml/l when 1-2 pustules/leaf","Monitor every 5 days - followup logic","Use resistant variety HD 2967","From Area/Production - yield target 3.5 t/ha"], escalate_if: "rust >10% leaf area", followup_days: 5, chemical: "Propiconazole 25% EC @1ml/l", safety: "15 days waiting period" },
  "Powdery Mildew": { crop: "Wheat", steps: ["Spray Wettable Sulphur @3g/l","Avoid dense sowing"], escalate_if: "white powder spreads", followup_days: 5, chemical: "Wettable Sulphur @3g/l", safety: "Low toxicity" },
  "Turcicum Leaf Blight": { crop: "Maize", steps: ["Spray Mancozeb @2.5g/l","Use resistant hybrid"], escalate_if: "blight >25% leaf area", followup_days: 7, chemical: "Mancozeb 75% WP @2.5g/l", safety: "PPE" },
  "Fall Armyworm": { crop: "Maize", steps: ["Install pheromone traps @5/acre","Spray Emamectin Benzoate @0.4g/l","Apply sand + lime mixture in whorl"], escalate_if: "damage >10% plants", followup_days: 3, chemical: "Emamectin Benzoate 5% SG @0.4g/l", safety: "Toxic - full PPE" },
  "Tikka Disease": { crop: "Groundnut", steps: ["Spray Chlorothalonil @2g/l","Follow crop rotation"], escalate_if: "leaf spots >20%", followup_days: 7, chemical: "Chlorothalonil 75% WP @2g/l", safety: "Moderate" },
  "Early Blight": { crop: "Tomato", steps: ["Remove infected leaves - destroy outside field","Spray Mancozeb 75% + Copper Oxychloride","Maintain spacing 60x45 cm","Avoid overhead irrigation","Soil_Moisture_Percent check - avoid >35%"], escalate_if: "spreading after 5 days", followup_days: 3, chemical: "Mancozeb 75% WP @2g/l + Copper Oxychloride", safety: "Wear gloves & mask" },
  "Late Blight": { crop: "Tomato", steps: ["Spray Metalaxyl + Mancozeb @2g/l","Avoid planting during high humidity"], escalate_if: "rapid spread within 2 days", followup_days: 2, chemical: "Metalaxyl 8% + Mancozeb 64% WP", safety: "Toxic - PPE" },
  "Purple Blotch": { crop: "Onion", steps: ["Spray Mancozeb @2g/l","Avoid excess irrigation"], escalate_if: "blotch >15% leaves", followup_days: 5, chemical: "Mancozeb 75% WP", safety: "Moderate" },
  "Sigatoka": { crop: "Banana", steps: ["Remove affected leaves","Spray Propiconazole @1ml/l","Drain excess water"], escalate_if: "new leaves infected after 7 days", followup_days: 7, chemical: "Propiconazole 25% EC", safety: "PPE" },
  "Mosaic": { crop: "Papaya", steps: ["Control aphid vector with Imidacloprid","Remove infected plants & burn","Use net house for nursery"], escalate_if: "mosaic >10% plants", followup_days: 5, chemical: "Vector control only - Imidacloprid for aphids", safety: "N/A" },
  "Wilt_Chickpea": { crop: "Chickpea", steps: ["Seed treatment Trichoderma @10g/kg","Use resistant variety","Deep ploughing in summer"], escalate_if: "wilting >10% area", followup_days: 7, chemical: "Trichoderma viride - bio", safety: "Safe - bio agent" },
  "Pod Borer": { crop: "Pigeon Pea", steps: ["Install pheromone traps @5/acre","Spray Emamectin Benzoate @0.4g/l","ETL 2 larvae/plant or 5% pod damage"], escalate_if: "pod damage >5%", followup_days: 5, chemical: "Emamectin Benzoate 5% SG", safety: "Toxic - PPE" },
  "Nutrient Deficiency": { crop: "General", steps: ["Check Soil_Nutrient_Analysis - If N<80=Urea @120kg/ha, P<50=DAP @60kg/ha, K<100=MOP @50kg/ha","If pH<6=Lime @200kg/ha, pH>8.5=Gypsum @100kg/ha","From District|Crop|Season|Area|Production|Yield - calculate need: Area * recommended dose","Apply FYM 5t/ha if Organic Carbon <0.5%"], escalate_if: "deficiency persists after 15 days", followup_days: 15, chemical: "Urea/DAP/MOP as per Soil Health Card from soilhealth.dac.gov.in", safety: "Follow label - don't mix" }
};

export const ALL_CROPS = ["Rice","Wheat","Sorghum","Pearl Millet","Maize","Pigeon Pea","Chickpea","Groundnut","Cotton","Soybean","Sugarcane","Banana","Barley","Black Gram","Green Gram","Lentil","Mustard","Sunflower","Safflower","Onion","Tomato","Papaya","Coconut","Watermelon","Muskmelon","Mango","Jute","Coffee","Mothbeans"];

export function searchAdvisory(diseaseName) {
  return ADVISORY_DB[diseaseName] || ADVISORY_DB["Nutrient Deficiency"];
}